Fixed custom thread snippet
The custom thread example fails because there is no message queue attached.

The exception is:
```java
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
```